## REMEMBER TO SET UP YOUR GIT REPO FOR TRAVIS
## Go to: https://travis-ci.org/I2PC for details
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: cd src/ontology && sh run.sh make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - coss@cnb.csic.es
    - isanchez@cnb.csic.es